use crate::m20250807_202824_init::*;
use crate::m20251116_000000_book_club_enhancements;
use crate::m20251116_000000_book_club_enhancements::*;
use crate::m20260116_000000_rewrite_media_annotations::*;
use crate::m20260118_204601_add_bookmark_created_at;
use crate::sqlite_extra::{sqlite_drop_indexes, sqlite_quote_ident};
use sea_orm::DatabaseBackend;
use sea_orm_migration::prelude::*;
// this migration will convert all the da_ime to timestamp_with_offset to be consistent with the rest of the codebase and to be able to store timezone information.
// It will also be compatible with the existing data, as the date_time will be converted to timestamp_with_offset with a default timezone of UTC.

#[derive(DeriveMigrationName)]
pub struct Migration;

const SQLITE_DATETIME_COLUMNS: [(&str, &str); 51] = [
	("users", "created_at"),
	("users", "deleted_at"),
	("api_keys", "created_at"),
	("api_keys", "expires_at"),
	("api_keys", "last_used_at"),
	("book_clubs", "created_at"),
	("emailers", "last_used_at"),
	("jobs", "created_at"),
	("jobs", "completed_at"),
	("server_invitations", "created_at"),
	("server_invitations", "expires_at"),
	("libraries", "created_at"),
	("libraries", "updated_at"),
	("libraries", "last_scanned_at"),
	("series", "created_at"),
	("series", "updated_at"),
	("series", "deleted_at"),
	("media", "created_at"),
	("media", "updated_at"),
	("media", "modified_at"),
	("media", "deleted_at"),
	("refresh_tokens", "created_at"),
	("refresh_tokens", "expires_at"),
	("sessions", "created_at"),
	("sessions", "expiry_time"),
	("user_login_activity", "timestamp"),
	("favorite_libraries", "favorited_at"),
	("favorite_media", "favorited_at"),
	("favorite_series", "favorited_at"),
	("last_library_visits", "timestamp"),
	("logs", "timestamp"),
	("emailer_send_records", "sent_at"),
	("library_scan_records", "timestamp"),
	("reading_sessions", "started_at"),
	("reading_sessions", "updated_at"),
	("finished_reading_sessions", "started_at"),
	("finished_reading_sessions", "completed_at"),
	("book_club_members", "joined_at"),
	("book_club_books", "completed_at"),
	("book_club_books", "added_at"),
	("book_club_book_suggestions", "resolved_at"),
	("book_club_book_suggestions", "created_at"),
	("book_club_book_suggestion_likes", "timestamp"),
	("book_club_discussions", "created_at"),
	("book_club_discussion_message", "timestamp"),
	("book_club_discussion_message", "edited_at"),
	("book_club_discussion_message_reactions", "created_at"),
	("custom_emojis", "created_at"),
	("media_annotations", "created_at"),
	("media_annotations", "updated_at"),
	("bookmarks", "created_at"),
];

async fn sqlite_alter_column_type(
	manager: &SchemaManager<'_>,
	table_name: &str,
	column_name: &str,
) -> Result<(), DbErr> {
	let quoted_table = sqlite_quote_ident(table_name);
	let quoted_column = sqlite_quote_ident(column_name);
	let temp_column_name = format!("{column_name}__tmp_tz");
	let quoted_temp_column = sqlite_quote_ident(&temp_column_name);

	let sql = format!(
		r#"
			ALTER TABLE {table} ADD COLUMN {temp_column} timestamp_with_timezone_text;
			UPDATE {table}
			SET {temp_column} = CASE
				WHEN {column} IS NULL THEN NULL
				ELSE strftime('%Y-%m-%dT%H:%M:%fZ', {column})
			END;
			ALTER TABLE {table} DROP COLUMN {column};
			ALTER TABLE {table} RENAME COLUMN {temp_column} TO {column};
		"#,
		table = quoted_table,
		column = quoted_column,
		temp_column = quoted_temp_column,
	);

	manager.get_connection().execute_unprepared(&sql).await?;

	Ok(())
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		if manager.get_database_backend() == DatabaseBackend::Sqlite {
			sqlite_drop_indexes(
				manager,
				"book_club_discussion_message",
				"idx_bcdm_discussion_ts",
			)
			.await?;

			for (table_name, column_name) in SQLITE_DATETIME_COLUMNS {
				sqlite_alter_column_type(manager, table_name, column_name).await?;
			}

			return Ok(());
		}
		if manager.get_database_backend() == DatabaseBackend::Postgres {
			manager
				.alter_table(
					Table::alter()
						.table(Users::Table)
						.modify_column(
							ColumnDef::new(Users::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Users::Table)
						.modify_column(
							ColumnDef::new(Users::DeletedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(
							ColumnDef::new(ApiKeys::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(
							ColumnDef::new(ApiKeys::ExpiresAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(
							ColumnDef::new(ApiKeys::LastUsedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Emailers::Table)
						.modify_column(
							ColumnDef::new(Emailers::LastUsedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Jobs::Table)
						.modify_column(
							ColumnDef::new(Jobs::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Jobs::Table)
						.modify_column(
							ColumnDef::new(Jobs::CompletedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ServerInvitations::Table)
						.modify_column(
							ColumnDef::new(ServerInvitations::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ServerInvitations::Table)
						.modify_column(
							ColumnDef::new(ServerInvitations::ExpiresAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(
							ColumnDef::new(Libraries::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(
							ColumnDef::new(Libraries::UpdatedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(
							ColumnDef::new(Libraries::LastScannedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(
							ColumnDef::new(Series::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(
							ColumnDef::new(Series::UpdatedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(
							ColumnDef::new(Series::DeletedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(
							ColumnDef::new(Media::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(
							ColumnDef::new(Media::UpdatedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(
							ColumnDef::new(Media::ModifiedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(
							ColumnDef::new(Media::DeletedAt).timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::ExpiresAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::ExpiryTime)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(UserLoginActivity::Table)
						.modify_column(
							ColumnDef::new(UserLoginActivity::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteLibraries::Table)
						.modify_column(
							ColumnDef::new(FavoriteLibraries::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteMedia::Table)
						.modify_column(
							ColumnDef::new(FavoriteMedia::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FavoriteSeries::Table)
						.modify_column(
							ColumnDef::new(FavoriteSeries::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LastLibraryVisits::Table)
						.modify_column(
							ColumnDef::new(LastLibraryVisits::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Logs::Table)
						.modify_column(
							ColumnDef::new(Logs::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(EmailerSendRecords::Table)
						.modify_column(
							ColumnDef::new(EmailerSendRecords::SentAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(LibraryScanRecords::Table)
						.modify_column(
							ColumnDef::new(LibraryScanRecords::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::StartedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::UpdatedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::StartedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::CompletedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(EmailerSendRecords::Table)
						.modify_column(
							ColumnDef::new(EmailerSendRecords::SentAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteLibraries::Table)
						.modify_column(
							ColumnDef::new(FavoriteLibraries::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteMedia::Table)
						.modify_column(
							ColumnDef::new(FavoriteMedia::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteSeries::Table)
						.modify_column(
							ColumnDef::new(FavoriteSeries::FavoritedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::StartedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::CompletedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LastLibraryVisits::Table)
						.modify_column(
							ColumnDef::new(LastLibraryVisits::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LibraryScanRecords::Table)
						.modify_column(
							ColumnDef::new(LibraryScanRecords::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Logs::Table)
						.modify_column(
							ColumnDef::new(Logs::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::StartedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::UpdatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::ExpiresAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::ExpiryTime)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(UserLoginActivity::Table)
						.modify_column(
							ColumnDef::new(UserLoginActivity::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			// migration from book club enhancements

			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubMembers::Table)
						.modify_column(
							ColumnDef::new(BookClubMembers::JoinedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubBooks::Table)
					.modify_column(
						ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubBooks::CompletedAt)
							.timestamp_with_time_zone(),
					)
					.to_owned(),
			)
			.await?;
			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubBooks::Table)
					.modify_column(
						ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubBooks::AddedAt)
							.timestamp_with_time_zone()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestions::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestions::ResolvedAt)
								.timestamp_with_time_zone(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestions::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestions::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestionLikes::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestionLikes::Timestamp)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubDiscussions::Table)
						.modify_column(
							ColumnDef::new(BookClubDiscussions::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::Table)
					.modify_column(
						ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::Timestamp)
							.timestamp_with_time_zone()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::Table)
					.modify_column(
						ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::EditedAt)
							.timestamp_with_time_zone(),
					)
					.to_owned(),
			)
			.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubDiscussionMessageReactions::Table)
						.modify_column(
							ColumnDef::new(BookClubDiscussionMessageReactions::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(CustomEmojis::Table)
						.modify_column(
							ColumnDef::new(CustomEmojis::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(MediaAnnotations::Table)
						.modify_column(
							ColumnDef::new(MediaAnnotations::CreatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(MediaAnnotations::Table)
						.modify_column(
							ColumnDef::new(MediaAnnotations::UpdatedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20260118_204601_add_bookmark_created_at::Bookmarks::Table)
					.modify_column(
						ColumnDef::new(m20260118_204601_add_bookmark_created_at::Bookmarks::CreatedAt)
							.timestamp_with_time_zone()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;
		}
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		if manager.get_database_backend() == DatabaseBackend::Postgres {
			manager
			.alter_table(
				Table::alter()
					.table(m20260118_204601_add_bookmark_created_at::Bookmarks::Table)
					.modify_column(
						ColumnDef::new(m20260118_204601_add_bookmark_created_at::Bookmarks::CreatedAt).date_time().not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
				.alter_table(
					Table::alter()
						.table(MediaAnnotations::Table)
						.modify_column(
							ColumnDef::new(MediaAnnotations::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(MediaAnnotations::Table)
						.modify_column(
							ColumnDef::new(MediaAnnotations::UpdatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::Table)
					.modify_column(
						ColumnDef::new(OldBookClubDiscussionMessage::CreatedAt)
							.date_time()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubDiscussionMessage::Table)
					.modify_column(
						ColumnDef::new(OldBookClubDiscussionMessage::UpdatedAt)
							.date_time()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(CustomEmojis::Table)
						.modify_column(
							ColumnDef::new(CustomEmojis::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubDiscussionMessageReactions::Table)
						.modify_column(
							ColumnDef::new(BookClubDiscussionMessageReactions::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubDiscussions::Table)
						.modify_column(
							ColumnDef::new(BookClubDiscussions::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestionLikes::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestionLikes::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestions::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestions::ResolvedAt)
								.date_time(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubBookSuggestions::Table)
						.modify_column(
							ColumnDef::new(BookClubBookSuggestions::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubBooks::Table)
					.modify_column(ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubBooks::CompletedAt).date_time())
					.to_owned(),
			)
			.await?;

			manager
			.alter_table(
				Table::alter()
					.table(m20251116_000000_book_club_enhancements::BookClubBooks::Table)
					.modify_column(
						ColumnDef::new(m20251116_000000_book_club_enhancements::BookClubBooks::AddedAt)
							.date_time()
							.not_null(),
					)
					.to_owned(),
			)
			.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubMembers::Table)
						.modify_column(
							ColumnDef::new(BookClubMembers::JoinedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;

			// migration from init
			manager
				.alter_table(
					Table::alter()
						.table(UserLoginActivity::Table)
						.modify_column(
							ColumnDef::new(UserLoginActivity::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::ExpiryTime).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::ExpiresAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::StartedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::UpdatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Logs::Table)
						.modify_column(
							ColumnDef::new(Logs::Timestamp).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(LibraryScanRecords::Table)
						.modify_column(
							ColumnDef::new(LibraryScanRecords::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LastLibraryVisits::Table)
						.modify_column(
							ColumnDef::new(LastLibraryVisits::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::StartedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::CompletedAt)
								.timestamp_with_time_zone()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FavoriteSeries::Table)
						.modify_column(
							ColumnDef::new(FavoriteSeries::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteMedia::Table)
						.modify_column(
							ColumnDef::new(FavoriteMedia::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteLibraries::Table)
						.modify_column(
							ColumnDef::new(FavoriteLibraries::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(EmailerSendRecords::Table)
						.modify_column(
							ColumnDef::new(EmailerSendRecords::SentAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::StartedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FinishedReadingSessions::Table)
						.modify_column(
							ColumnDef::new(FinishedReadingSessions::CompletedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ReadingSessions::Table)
						.modify_column(
							ColumnDef::new(ReadingSessions::StartedAt)
								.date_time()
								.not_null(),
						)
						.modify_column(
							ColumnDef::new(ReadingSessions::UpdatedAt).date_time(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LibraryScanRecords::Table)
						.modify_column(
							ColumnDef::new(LibraryScanRecords::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(EmailerSendRecords::Table)
						.modify_column(
							ColumnDef::new(EmailerSendRecords::SentAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Logs::Table)
						.modify_column(
							ColumnDef::new(Logs::Timestamp).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(LastLibraryVisits::Table)
						.modify_column(
							ColumnDef::new(LastLibraryVisits::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(FavoriteSeries::Table)
						.modify_column(
							ColumnDef::new(FavoriteSeries::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteMedia::Table)
						.modify_column(
							ColumnDef::new(FavoriteMedia::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(FavoriteLibraries::Table)
						.modify_column(
							ColumnDef::new(FavoriteLibraries::FavoritedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(UserLoginActivity::Table)
						.modify_column(
							ColumnDef::new(UserLoginActivity::Timestamp)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Sessions::Table)
						.modify_column(
							ColumnDef::new(Sessions::ExpiryTime).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(RefreshTokens::Table)
						.modify_column(
							ColumnDef::new(RefreshTokens::ExpiresAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(
							ColumnDef::new(Media::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(ColumnDef::new(Media::UpdatedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(ColumnDef::new(Media::ModifiedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Media::Table)
						.modify_column(ColumnDef::new(Media::DeletedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(
							ColumnDef::new(Series::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(ColumnDef::new(Series::UpdatedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Series::Table)
						.modify_column(ColumnDef::new(Series::DeletedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(
							ColumnDef::new(Libraries::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(ColumnDef::new(Libraries::UpdatedAt).date_time())
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Libraries::Table)
						.modify_column(
							ColumnDef::new(Libraries::LastScannedAt).date_time(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ServerInvitations::Table)
						.modify_column(
							ColumnDef::new(ServerInvitations::CreatedAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ServerInvitations::Table)
						.modify_column(
							ColumnDef::new(ServerInvitations::ExpiresAt)
								.date_time()
								.not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Jobs::Table)
						.modify_column(
							ColumnDef::new(Jobs::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(Jobs::Table)
						.modify_column(ColumnDef::new(Jobs::CompletedAt).date_time())
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Emailers::Table)
						.modify_column(ColumnDef::new(Emailers::LastUsedAt).date_time())
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(BookClubs::Table)
						.modify_column(
							ColumnDef::new(BookClubs::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(
							ColumnDef::new(ApiKeys::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(ColumnDef::new(ApiKeys::LastUsedAt).date_time())
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(ApiKeys::Table)
						.modify_column(ColumnDef::new(ApiKeys::LastUsedAt).date_time())
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(Users::Table)
						.modify_column(
							ColumnDef::new(Users::CreatedAt).date_time().not_null(),
						)
						.to_owned(),
				)
				.await?;
		}
		Ok(())
	}
}
