use sea_orm::DatabaseBackend;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		if manager.get_database_backend() == DatabaseBackend::Postgres {
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_analysis"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_analysis-media")
								.from_tbl(sea_query::Alias::new("media_analysis"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("page_analysis"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-page_analysis-media")
								.from_tbl(sea_query::Alias::new("page_analysis"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_book_suggestions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestions-club")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestions",
								))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_book_suggestions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestions-book")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestions",
								))
								.from_col(sea_query::Alias::new("book_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_book_suggestions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestions-member")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestions",
								))
								.from_col(sea_query::Alias::new("member_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_book_suggestions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestions-resolved_by")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestions",
								))
								.from_col(sea_query::Alias::new("resolved_by_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_book_suggestion_likes"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestion_likes-member")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestion_likes",
								))
								.from_col(sea_query::Alias::new("member_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestion_likes-suggestion")
								.from_tbl(sea_query::Alias::new(
									"book_club_book_suggestion_likes",
								))
								.from_col(sea_query::Alias::new("suggestion_id"))
								.to_tbl(sea_query::Alias::new(
									"book_club_book_suggestions",
								))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_discussions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_discussions-book")
								.from_tbl(sea_query::Alias::new("book_club_discussions"))
								.from_col(sea_query::Alias::new("book_club_book_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_discussions-book_club")
								.from_tbl(sea_query::Alias::new("book_club_discussions"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_members"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_members-book_club")
								.from_tbl(sea_query::Alias::new("book_club_members"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_members"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_members-user")
								.from_tbl(sea_query::Alias::new("book_club_members"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_member_favorite_books"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_member_favorite_books-member")
								.from_tbl(sea_query::Alias::new(
									"book_club_member_favorite_books",
								))
								.from_col(sea_query::Alias::new("member_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_member_favorite_books"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_member_favorite_books-book")
								.from_tbl(sea_query::Alias::new(
									"book_club_member_favorite_books",
								))
								.from_col(sea_query::Alias::new("book_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_invitations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_invitations-book_club")
								.from_tbl(sea_query::Alias::new("book_club_invitations"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_invitations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_invitations-book_user")
								.from_tbl(sea_query::Alias::new("book_club_invitations"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_books"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_books-book_club")
								.from_tbl(sea_query::Alias::new("book_club_books"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new(
							"book_club_discussion_message_reactions",
						))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdmr-member")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message_reactions",
								))
								.from_col(sea_query::Alias::new("member_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdmr-message")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message_reactions",
								))
								.from_col(sea_query::Alias::new("message_id"))
								.to_tbl(sea_query::Alias::new("book_club_discussions"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_books"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_books-book_entity")
								.from_tbl(sea_query::Alias::new("book_club_books"))
								.from_col(sea_query::Alias::new("book_entity_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("custom_emojis"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-custom_emojis-created_by")
								.from_tbl(sea_query::Alias::new("custom_emojis"))
								.from_col(sea_query::Alias::new("created_by_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("scheduled_job_libraries"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-scheduled_job_libraries-library")
								.from_tbl(sea_query::Alias::new(
									"scheduled_job_libraries",
								))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_schedules"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("idx_bcm_user_club")
								.from_tbl(sea_query::Alias::new("book_club_schedules"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bookmarks-media")
								.from_tbl(sea_query::Alias::new("bookmarks"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bookmarks-user")
								.from_tbl(sea_query::Alias::new("bookmarks"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("users"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-users-user_preferences")
								.from_tbl(sea_query::Alias::new("users"))
								.from_col(sea_query::Alias::new("user_preferences_id"))
								.to_tbl(sea_query::Alias::new("user_preferences"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("age_restrictions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-age_restrictions-user")
								.from_tbl(sea_query::Alias::new("age_restrictions"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("api_keys"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-api_keys-user")
								.from_tbl(sea_query::Alias::new("api_keys"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("libraries"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-libraries-config")
								.from_tbl(sea_query::Alias::new("libraries"))
								.from_col(sea_query::Alias::new("config_id"))
								.to_tbl(sea_query::Alias::new("library_configs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::NoAction)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-series-library")
								.from_tbl(sea_query::Alias::new("series"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media-series")
								.from_tbl(sea_query::Alias::new("media"))
								.from_col(sea_query::Alias::new("series_id"))
								.to_tbl(sea_query::Alias::new("series"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("refresh_tokens"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-refresh_tokens-user")
								.from_tbl(sea_query::Alias::new("refresh_tokens"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-sessions-user")
								.from_tbl(sea_query::Alias::new("sessions"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("user_login_activity"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-user_login_activity-user")
								.from_tbl(sea_query::Alias::new("user_login_activity"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("pk-favorite_libraries")
								.from_tbl(sea_query::Alias::new("favorite_libraries"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-favorite_libraries-library")
								.from_tbl(sea_query::Alias::new("favorite_libraries"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("pk-favorite_media")
								.from_tbl(sea_query::Alias::new("favorite_media"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-favorite_media-media")
								.from_tbl(sea_query::Alias::new("favorite_media"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("pk-favorite_series")
								.from_tbl(sea_query::Alias::new("favorite_series"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-favorite_series-series")
								.from_tbl(sea_query::Alias::new("favorite_series"))
								.from_col(sea_query::Alias::new("series_id"))
								.to_tbl(sea_query::Alias::new("series"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_exclusions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_exclusions-library")
								.from_tbl(sea_query::Alias::new("library_exclusions"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_exclusions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_exclusions-user")
								.from_tbl(sea_query::Alias::new("library_exclusions"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_tags-library")
								.from_tbl(sea_query::Alias::new("library_tags"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_tags-tag")
								.from_tbl(sea_query::Alias::new("library_tags"))
								.from_col(sea_query::Alias::new("tag_id"))
								.to_tbl(sea_query::Alias::new("tags"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_tags-media")
								.from_tbl(sea_query::Alias::new("media_tags"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_tags-tag")
								.from_tbl(sea_query::Alias::new("media_tags"))
								.from_col(sea_query::Alias::new("tag_id"))
								.to_tbl(sea_query::Alias::new("tags"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-series_tags-series")
								.from_tbl(sea_query::Alias::new("series_tags"))
								.from_col(sea_query::Alias::new("series_id"))
								.to_tbl(sea_query::Alias::new("series"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-series_tags-tag")
								.from_tbl(sea_query::Alias::new("series_tags"))
								.from_col(sea_query::Alias::new("tag_id"))
								.to_tbl(sea_query::Alias::new("tags"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("last_library_visits"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-last_library_visits-library")
								.from_tbl(sea_query::Alias::new("last_library_visits"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("last_library_visits"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-last_library_visits-user")
								.from_tbl(sea_query::Alias::new("last_library_visits"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reviews"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-reviews-media")
								.from_tbl(sea_query::Alias::new("reviews"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reviews"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-reviews-user")
								.from_tbl(sea_query::Alias::new("reviews"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("logs"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-logs-job")
								.from_tbl(sea_query::Alias::new("logs"))
								.from_col(sea_query::Alias::new("job_id"))
								.to_tbl(sea_query::Alias::new("jobs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-emailer_send_records-emailer")
								.from_tbl(sea_query::Alias::new("favorite_libraries"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_scan_records-library")
								.from_tbl(sea_query::Alias::new("library_tags"))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_annotations-user")
								.from_tbl(sea_query::Alias::new("media_annotations"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_metadata"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_metadata-media")
								.from_tbl(sea_query::Alias::new("media_metadata"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("page_analysis"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("media_metadata_media_id_idx")
								.from_tbl(sea_query::Alias::new("page_analysis"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_metadata"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-series_metadata-series")
								.from_tbl(sea_query::Alias::new("series_metadata"))
								.from_col(sea_query::Alias::new("series_id"))
								.to_tbl(sea_query::Alias::new("series"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("series_metadata_series_id_idx")
								.from_tbl(sea_query::Alias::new("reading_sessions"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-reading_sessions-device")
								.from_tbl(sea_query::Alias::new("reading_sessions"))
								.from_col(sea_query::Alias::new("device_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("reading_session_media_id_user_id_idx")
								.from_tbl(sea_query::Alias::new("reading_sessions"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("smart_lists"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-smart_lists-user")
								.from_tbl(sea_query::Alias::new("smart_lists"))
								.from_col(sea_query::Alias::new("creator_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("smart_list_views"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-smart_list_access_rules-smart_list")
								.from_tbl(sea_query::Alias::new("smart_list_views"))
								.from_col(sea_query::Alias::new("list_id"))
								.to_tbl(sea_query::Alias::new("smart_lists"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("smart_list_views"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-smart_list_access_rules-user")
								.from_tbl(sea_query::Alias::new("smart_list_views"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_schedules"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_schedules-book_club")
								.from_tbl(sea_query::Alias::new("book_club_schedules"))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_discussions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_book_suggestion_likes-suggestion")
								.from_tbl(sea_query::Alias::new("book_club_discussions"))
								.from_col(sea_query::Alias::new("book_id"))
								.to_tbl(sea_query::Alias::new("book_club_books"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_discussion_message"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-book_club_discussion_message-parent")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message",
								))
								.from_col(sea_query::Alias::new("parent_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdm-reply_to")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message",
								))
								.from_col(sea_query::Alias::new("reply_to_message_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdm-book_club")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message",
								))
								.from_col(sea_query::Alias::new("book_club_id"))
								.to_tbl(sea_query::Alias::new("book_clubs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdm-discussion")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message",
								))
								.from_col(sea_query::Alias::new("discussion_id"))
								.to_tbl(sea_query::Alias::new("book_club_discussions"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bcdm-member")
								.from_tbl(sea_query::Alias::new(
									"book_club_discussion_message",
								))
								.from_col(sea_query::Alias::new("member_id"))
								.to_tbl(sea_query::Alias::new("book_club_members"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-bookmarks-parent")
								.from_tbl(sea_query::Alias::new("bookmarks"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-favorite_media-user")
								.from_tbl(sea_query::Alias::new("favorite_media"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-favorite_series-user")
								.from_tbl(sea_query::Alias::new("favorite_series"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("finished_reading_sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-finished_reading_sessions-media")
								.from_tbl(sea_query::Alias::new(
									"finished_reading_sessions",
								))
								.from_col(sea_query::Alias::new("library_id"))
								.to_tbl(sea_query::Alias::new("libraries"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-finished_reading_sessions-user")
								.from_tbl(sea_query::Alias::new(
									"finished_reading_sessions",
								))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_scan_records"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-library_scan_records-job")
								.from_tbl(sea_query::Alias::new("library_scan_records"))
								.from_col(sea_query::Alias::new("job_id"))
								.to_tbl(sea_query::Alias::new("jobs"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-media_annotations-media")
								.from_tbl(sea_query::Alias::new("media_annotations"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-reading_sessions-user")
								.from_tbl(sea_query::Alias::new("reading_sessions"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("smart_list_views"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-smart_list_views-smart_list")
								.from_tbl(sea_query::Alias::new("smart_list_views"))
								.from_col(sea_query::Alias::new("list_id"))
								.to_tbl(sea_query::Alias::new("smart_lists"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;

			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_metadata"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk-scheduled_job_libraries-job_config")
								.from_tbl(sea_query::Alias::new("series_metadata"))
								.from_col(sea_query::Alias::new("series_id"))
								.to_tbl(sea_query::Alias::new("series"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk_media_annotations_media_id")
								.from_tbl(sea_query::Alias::new("media_annotations"))
								.from_col(sea_query::Alias::new("media_id"))
								.to_tbl(sea_query::Alias::new("media"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("fk_media_annotations_user_id")
								.from_tbl(sea_query::Alias::new("media_annotations"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("old_media_annotations"))
						.add_foreign_key(
							TableForeignKey::new()
								.name("idx_media_annotations_user_media")
								.from_tbl(sea_query::Alias::new("old_media_annotations"))
								.from_col(sea_query::Alias::new("user_id"))
								.to_tbl(sea_query::Alias::new("users"))
								.to_col(sea_query::Alias::new("id"))
								.on_delete(ForeignKeyAction::Cascade)
								.on_update(ForeignKeyAction::NoAction),
						)
						.to_owned(),
				)
				.await?;
		}
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		if manager.get_database_backend() == DatabaseBackend::Postgres {
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_analysis"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-media_analysis-media",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("page_analysis"))
						.drop_foreign_key(sea_query::Alias::new("fk-page_analysis-media"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_members"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_members-book_club",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_members"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_members-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_invitations"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_invitations-book_club",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_books"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_member_favorite_books-member",
						))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_member_favorite_books-book",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_books"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_books-book_entity",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("custom_emojis"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_book_suggestions-club",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_schedules"))
						.drop_foreign_key(sea_query::Alias::new("idx_bcm_user_club"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.drop_foreign_key(sea_query::Alias::new("fk-bookmarks-media"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.drop_foreign_key(sea_query::Alias::new("fk-bookmarks-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("users"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-users-user_preferences",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("age_restrictions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-age_restrictions-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("api_keys"))
						.drop_foreign_key(sea_query::Alias::new("fk-api_keys-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("libraries"))
						.drop_foreign_key(sea_query::Alias::new("fk-libraries-config"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series"))
						.drop_foreign_key(sea_query::Alias::new("fk-series-library"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media"))
						.drop_foreign_key(sea_query::Alias::new("fk-media-series"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("refresh_tokens"))
						.drop_foreign_key(sea_query::Alias::new("fk-refresh_tokens-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("sessions"))
						.drop_foreign_key(sea_query::Alias::new("fk-sessions-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("user_login_activity"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-user_login_activity-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.drop_foreign_key(sea_query::Alias::new("pk-favorite_libraries"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-favorite_libraries-library",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.drop_foreign_key(sea_query::Alias::new("pk-favorite_media"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-favorite_media-media",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.drop_foreign_key(sea_query::Alias::new("pk-favorite_series"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-favorite_series-series",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_exclusions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-library_exclusions-library",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_exclusions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-library_exclusions-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-library_tags-library",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.drop_foreign_key(sea_query::Alias::new("fk-library_tags-tag"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_tags"))
						.drop_foreign_key(sea_query::Alias::new("fk-media_tags-media"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_tags"))
						.drop_foreign_key(sea_query::Alias::new("fk-media_tags-tag"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_tags"))
						.drop_foreign_key(sea_query::Alias::new("fk-series_tags-series"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_tags"))
						.drop_foreign_key(sea_query::Alias::new("fk-series_tags-tag"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("last_library_visits"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-last_library_visits-library",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("last_library_visits"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-last_library_visits-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reviews"))
						.drop_foreign_key(sea_query::Alias::new("fk-reviews-media"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reviews"))
						.drop_foreign_key(sea_query::Alias::new("fk-reviews-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("logs"))
						.drop_foreign_key(sea_query::Alias::new("fk-logs-job"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_libraries"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-emailer_send_records-emailer",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_tags"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-library_scan_records-library",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-media_annotations-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_metadata"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-media_metadata-media",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("page_analysis"))
						.drop_foreign_key(sea_query::Alias::new(
							"media_metadata_media_id_idx",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_metadata"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-series_metadata-series",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.drop_foreign_key(sea_query::Alias::new(
							"series_metadata_series_id_idx",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-reading_sessions-device",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.drop_foreign_key(sea_query::Alias::new(
							"reading_session_media_id_user_id_idx",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("smart_list_views"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-smart_list_access_rules-smart_list",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_schedules"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_schedules-book_club",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("book_club_discussions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_book_suggestion_likes-suggestion",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("bookmarks"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-book_club_discussion_message-parent",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_media"))
						.drop_foreign_key(sea_query::Alias::new("fk-favorite_media-user"))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("favorite_series"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-favorite_series-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("last_library_visits"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-finished_reading_sessions-media",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("library_scan_records"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-library_scan_records-job",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-media_annotations-media",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("reading_sessions"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-reading_sessions-user",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("series_metadata"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk-scheduled_job_libraries-job_config",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk_media_annotations_media_id",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("media_annotations"))
						.drop_foreign_key(sea_query::Alias::new(
							"fk_media_annotations_user_id",
						))
						.to_owned(),
				)
				.await?;
			manager
				.alter_table(
					Table::alter()
						.table(sea_query::Alias::new("old_media_annotations"))
						.drop_foreign_key(sea_query::Alias::new(
							"idx_media_annotations_user_media",
						))
						.to_owned(),
				)
				.await?;
		}
		Ok(())
	}
}
